// Generated by Wrangler by running `wrangler types -c test-worker/wrangler.json`

interface Env {
	STORAGE_TEST: DurableObjectNamespace<import("./test-worker/index").StorageTest>;
	ALARM_TEST: DurableObjectNamespace<import("./test-worker/index").AlarmTest>;
	SQL_TEST: DurableObjectNamespace<import("./test-worker/index").SqlTest>;
}
